### ISSUE TITLE
Can't install one of the extension: 'thejustinwalsh.textproto-grammer' not found

### ISSUE THREAD

**Issue by ProgrammingLife** [astrochili/vscode-defold#32]
When I trying to setup a Defold kit I get: 
```
[info] Error: Extension 'thejustinwalsh.textproto-grammer' not found.
```

So I get unrecognized objects "go", "hash", "require" and all others: 
```
TypeError: Unknown global 'go' [Luau]
```

**Comment by astrochili** [comment]
Hello

Strange message about extension, because the extension is [available in the marketplace](https://marketplace.visualstudio.com/items?itemName=thejustinwalsh.textproto-grammer) and there should be no problem to install it.

About the second one - not sure if it's about the Defold Kit, because there is "**Luau**" at the end of the log message.

About the third one I also don't have idea, it's not Deolf Kit messages. Please, turn off all the third-party extensions outside the Defold Kit list and try again 🙏

**Comment by astrochili** [comment]
Both your messages are from the Luau extension — https://github.com/search?q=%22Failed+to+load+sourcemap.json+for+workspace%22&type=code.

It's now about Defold or Defold Kit. You need to disable Luau extension if you don't want to see these messages in the Defold workspace.
