### ISSUE TITLE
require invoked from pcall can't load a module

### ISSUE THREAD

**Issue by kamchatka-volcano** [astrochili/vscode-defold#44]
Hi, for some reason, loading modules with `pcall` doesn't work from the Defold kit, although it loads fine when building from the Defold editor. Some libraries use this pattern to select between local and global dependencies by checking the status code of `pcall`. For instance, I had to patch the penlight library to use it with a Defold project from VSCode with the Defold kit.

Steps to reproduce:
- Create a project from the Desktop game template, and add a Lua module test.lua to the main directory like:
```
local M = {}
function M.test()
	print("Hello world")
end
return M
```
- Try to load it from the main.script:
```
local status, test = pcall(require, "main.test")
assert(test ~= nil)
```

Is it a limitation of the `bob` build tool?

**Comment by astrochili** [comment]
I'm not sure, but I think it's because the [local lua debugger](https://github.com/tomblind/local-lua-debugger-vscode/) uses `pcall` to catch exceptions and pause execution to show the current state like a breakpoint.

If you don't need a debugger, in theory you could add a [custom task](https://code.visualstudio.com/docs/editor/tasks) with dependency on `Defold Kit: Build to Launch` that would start the build with bob and then run the game directly, then pcall would work as usual.

**Comment by kamchatka-volcano** [comment]
I see, thanks for the explanation. I guess, I'll just continue using a patched library, as debugging is important to me.
